version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: yarn install --production
      - run: yarn build
      - run: yarn start
workflows:
  build:
    jobs:
      - build
  
