version: 2.1
jobs:
  InstallYarn:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install -g yarn@latest
      - run: yarn install
workflows:
  Install-Yarn:
    jobs:
      - InstallYarn
