version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
workflows:
  build:
    jobs:
      - build
  lint:
    jobs:
      - lint
  
