version: 2.1

orbs:
  node: circleci/node@5.0.2
jobs:
  InstallYarn:
    docker:
      - image: cimg/base:stable
    steps:
      
      - node/install-yarn
workflows:
  Install-Yarn:
    jobs:
      - InstallYarn
