version: 2.1
jobs:
  InstallYarn:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: node --version
      - run: npm -v
workflows:
  Install-Yarn:
    jobs:
      - InstallYarn
